name: Atualizar Goodreads no README

on:
  schedule:
    - cron: '0 0 * * *' # Executa automaticamente todos os dias à meia-noite (UTC)
  workflow_dispatch: # Permite que você rode o script manualmente

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      # Atualizado para v4 para resolver o aviso amarelinho
      - name: Checkout repository
        uses: actions/checkout@v4
        
      # Atualizado para v5 para resolver o aviso amarelinho
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Executar script Python
        run: python update_readme.py
        
      - name: Fazer commit e push das alterações
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          # Só faz o commit se houver alguma mudança real no arquivo
          git diff --quiet && git diff --staged --quiet || (git commit -m "docs: atualiza livro atual do goodreads" && git push)
